---
title: "Homework9KellyCraig"
author: "Kelly Craig"
date: "June 20, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r echo=FALSE, include =FALSE, results = 'hide'}
library(tidyverse)
library(GGally)
library(rgl)
library(caret)
Fires <- read_csv("C:/Users/Kelly/Documents/forestFiresTrain.csv")
```

```{r echo = TRUE}
#Using log area for anaylsis.
Fires <- mutate(Fires, logarea = log(area + 1))
hist(Fires$logarea)
Fires$logarea <- as.numeric(Fires$logarea)
```

```{r echo = TRUE}
#selecting data with temp, RH, wind, rain and y columns
Fires <- Fires %>% select(temp, RH, wind, rain, logarea)
GGally::ggpairs(Fires)
```

```{r echo = TRUE}
#Normalize data to control for different ranges
normalize <- function(x) {
  return((x - min(x)) / (max(x) - min(x)))
}

Fires$temp <- normalize(Fires$temp)
Fires$RH <- normalize(Fires$RH)
Fires$wind <- normalize(Fires$wind)
Fires$rain <- normalize(Fires$rain)
```

```{r echo = TRUE}
#make the simple linear regression model
fit1 <- lm(logarea ~ wind, data = Fires) 
fit1[[1]]

#Plot wind and log area
ggplot(Fires, aes(x = wind, y = logarea)) +
  geom_point() +
  geom_smooth(method = "lm") +
  geom_smooth(col = "red")

#Predict two values
predict1 <- predict(fit1, newdata1 = data.frame(wind = 0.1), se.fit=TRUE, interval= "prediction")
#Does not predict well. 
```

```{r echo = TRUE}
#make the multiple linear regression model
fit2 <- lm(logarea ~ RH + temp, data = Fires) 

#3d plot
grid.lines = 40
x.pred <- seq(min(Fires$RH), max(Fires$RH), length.out = grid.lines) 
y.pred <- seq(min(Fires$temp), max(Fires$temp), length.out = grid.lines) 
xy <- expand.grid(RH = x.pred, temp = y.pred) 

#predictions
z.pred <- matrix(predict(fit2, newdata = xy),
                 nrow = grid.lines, ncol = grid.lines)

# scatter plot with regression plane (rgl package)
plot3d(x = Fires$RH, y = Fires$temp, z = Fires$logarea,
       cex = 0.8, theta = 20, phi = 20, ticktype = "detailed",
       xlab = "RH", ylab = "temp", zlab =  "logarea")

#add surface 
surface3d(x = x.pred, y = y.pred, z = z.pred, color = "green")
```

```{r echo = TRUE}
#make the multiple linear regression model
fit3 <- lm(logarea ~ wind*temp*RH, data = Fires)
newdata <- data.frame(wind=0.3, temp=0.6, RH=0.3)
#predict values
predict3 <- predict(fit3, newdata1 = newdata)

CraigModel <- lm(logarea ~ wind*temp*RH, data = Fires)
```

